<a href="https://colab.research.google.com/github/Finch46/Finch46/blob/main/Stats_Assign_(Central_Tendency%26_Dispersion)_ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
from scipy import stats
import pandas as pd
import random

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

np.random.normal(loc=0.0, scale=1.0, size=None)  #you need to modify this code.

loc will be equal to mean, scale will be equal to std deviation, size will be equal to sample size.

In [3]:
random.seed(10)
rand_num = [random.randint(0,1000) for i in range(1000)]
 
print(rand_num[0:1000])

[585, 33, 439, 494, 591, 15, 211, 473, 832, 503, 843, 284, 669, 830, 164, 35, 533, 501, 335, 77, 255, 975, 975, 763, 369, 45, 430, 880, 142, 617, 363, 390, 431, 290, 846, 691, 268, 467, 178, 702, 310, 677, 371, 136, 467, 786, 880, 245, 992, 450, 628, 384, 45, 596, 4, 241, 137, 199, 963, 931, 310, 549, 374, 790, 919, 245, 321, 682, 562, 461, 446, 481, 66, 668, 598, 332, 864, 513, 160, 862, 229, 993, 422, 244, 37, 32, 508, 308, 837, 621, 673, 73, 546, 946, 875, 82, 153, 393, 580, 968, 383, 934, 615, 153, 115, 986, 794, 791, 98, 452, 170, 826, 195, 970, 357, 443, 993, 424, 456, 251, 697, 281, 146, 632, 534, 182, 885, 122, 273, 466, 309, 168, 676, 664, 965, 840, 178, 796, 180, 491, 791, 355, 335, 445, 229, 5, 557, 729, 44, 339, 918, 327, 248, 81, 268, 458, 414, 596, 162, 399, 942, 890, 507, 689, 914, 247, 753, 537, 932, 278, 532, 494, 616, 511, 64, 170, 501, 690, 472, 919, 410, 139, 430, 554, 598, 357, 551, 397, 501, 718, 169, 572, 451, 101, 991, 997, 425, 848, 36, 892, 2, 449, 548, 66, 51

In [4]:
np.random.normal(loc=100.0, scale=10.0, size=1000)

array([ 85.78507602, 103.48461278,  99.34995951,  93.33824156,
       117.77106678,  98.42486054,  92.10004949,  92.45915729,
        92.75884472, 106.20134095,  99.57840557, 105.11281881,
        97.57892565, 111.35962477, 109.96039358,  92.84516027,
       113.51553457,  96.29218495,  95.46978991, 103.88057657,
       110.2405547 ,  85.60038598,  96.47684255, 118.31647154,
        97.2784454 , 105.15706254,  99.77137641, 106.4399418 ,
        87.49950248,  91.6612912 , 109.99883746, 100.91628533,
       101.53801509, 107.11991692, 116.09562032,  92.35788264,
       100.39716672, 109.30260111,  91.37346904, 118.24856909,
        89.45067227, 111.8693301 ,  91.96013397,  94.4330154 ,
       106.35230089,  93.13688925, 104.80781909, 107.42503143,
       123.87523509,  96.63544863,  97.78912906, 106.70656286,
        83.38739886, 113.89140071,  92.98828266, 102.61587977,
        99.46202565,  99.06068328,  87.58337066,  99.92535471,
        99.70090477, 100.56075682, 112.62995012, 100.77

In [5]:
np.mean(rand_num)

499.242

Compute the **mean**, **median**, and **mode**

In [ ]:
rand_mean= np.mean(rand_num)
print("mean:", rand_mean)
rand_median = np.median(rand_num)
print("median:", rand_median)
rand_mode = stats.mode(rand_num)
print("mode:", rand_mode)


mean: 499.242
median: 491.0
mode: ModeResult(mode=array([501]), count=array([5]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
np.percentile(rand_num, 25)

249.5

In [ ]:
np.percentile(rand_num, 75)

740.0

In [ ]:
np.percentile(rand_num, 75) - np.percentile(rand_num, 25)

490.5

In [ ]:
stats.iqr(rand_num)

490.5

In [ ]:
print("minimum: ", min(rand_num))
print("maximum: ", max(rand_num))

minimum:  2
maximum:  998


In [ ]:
np.var(rand_num)

82747.84343600001

In [ ]:
np.std(rand_num)

287.6592488274973

In [ ]:
from scipy. stats import skew


In [6]:
from scipy. stats import kurtosis


In [ ]:
print(skew(rand_num))

0.00356384763032434


In [7]:
kurtosis(rand_num)

-1.1588433991168958

Compute the **variance** and **standard deviation**

Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
 x = np.arange(start=10, stop=20)
 x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([3,6,4,2,5,9,7,1,7,4])
y

array([3, 6, 4, 2, 5, 9, 7, 1, 7, 4])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
from scipy.stats.stats import pearsonr

In [ ]:
stats.pearsonr(x,y)

(0.1476507406862616, 0.6839637131477981)

In [ ]:
np.corrcoef(x,y)

array([[1.        , 0.14765074],
       [0.14765074, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = stats.pearsonr(x,y)
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
tips.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:


from numpy.random import randn
from numpy.random import seed
from scipy.stats import pearsonr

seed(1)

data1 = 20 * randn(1000) + 100
data2 = data1 + (10 * randn(1000) + 50)

corr, _ = pearsonr(data1, data2)
print('Pearsons correlation: %.3f' % corr)

Pearsons correlation: 0.888
